name: Run tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

# Cancel job when new commit is pushed for the same build
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
# https://github.com/OSGeo/gdal/pull/5460
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: ['11', '17','21']

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11/17/21 for x64
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          architecture: x64
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
